"""Conflict-reduction proof for sharded architecture ownership metadata."""

from __future__ import annotations

import hashlib
import json
import shutil
import subprocess
from pathlib import Path

from apm_cli.utils.git_env import get_git_executable, git_subprocess_env
from scripts.architecture_linter.registry import load_registry

ROOT = Path(__file__).parents[3]
STABLE_PATHS = (
    ".apm/instructions/architecture.instructions.md",
    ".github/instructions/architecture.instructions.md",
    "apm.lock.yaml",
)


def test_generated_architecture_projections_match_their_sources() -> None:
    """The deployed instruction and owner gate are generated byte-for-byte."""
    assert (ROOT / ".apm/instructions/architecture.instructions.md").read_bytes() == (
        ROOT / ".github/instructions/architecture.instructions.md"
    ).read_bytes()
    assert (
        ROOT / "packages/autopilot/autopilot-pr-merge-worker/scripts/owner_touch_gate.py"
    ).read_bytes() == (
        ROOT / ".agents/skills/autopilot-pr-merge-worker/scripts/owner_touch_gate.py"
    ).read_bytes()


def _git(repo: Path, *args: str) -> str:
    result = subprocess.run(
        [get_git_executable(), *args],
        cwd=repo,
        env=git_subprocess_env(),
        check=False,
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, result.stderr
    return result.stdout.strip()


def _digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _append_owner(repo: Path, shard: str, owner_id: str, selector: str) -> None:
    shard_path = repo / ".apm/architecture/owners" / shard
    document = json.loads(shard_path.read_text(encoding="ascii"))
    document["owners"].append(
        {
            "id": owner_id,
            "decision": f"Fixture decision {owner_id}",
            "owner": f"{selector} (FixtureOwner)",
            "selectors": [selector],
            "guards": [f"{owner_id}-guard"],
        }
    )
    shard_path.write_text(
        json.dumps(document, indent=2, ensure_ascii=True) + "\n",
        encoding="ascii",
    )
    source = repo / selector
    source.parent.mkdir(parents=True, exist_ok=True)
    source.write_text('OWNER = "fixture"\n', encoding="ascii")


def test_independent_owner_additions_merge_without_instruction_or_lock_conflicts(
    tmp_path: Path,
) -> None:
    """Different domain shards merge while stable guidance and its hash stay put."""
    repo = tmp_path / "repo"
    repo.mkdir()
    for relative in STABLE_PATHS:
        destination = repo / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(ROOT / relative, destination)
    shutil.copytree(
        ROOT / ".apm/architecture/owners",
        repo / ".apm/architecture/owners",
    )

    _git(repo, "init", "-q", "-b", "main")
    _git(repo, "config", "user.email", "fixture@example.invalid")
    _git(repo, "config", "user.name", "Fixture")
    _git(repo, "add", ".")
    _git(repo, "commit", "-q", "-m", "base")
    stable_digests = {relative: _digest(repo / relative) for relative in STABLE_PATHS}

    _git(repo, "checkout", "-q", "-b", "owner-core")
    _append_owner(
        repo,
        "core-runtime.json",
        "fixture-core-owner",
        "src/apm_cli/fixture_core_owner.py",
    )
    _git(repo, "add", ".")
    _git(repo, "commit", "-q", "-m", "add core owner")

    _git(repo, "checkout", "-q", "main")
    _git(repo, "checkout", "-q", "-b", "owner-marketplace")
    _append_owner(
        repo,
        "marketplace-plugins.json",
        "fixture-marketplace-owner",
        "src/apm_cli/fixture_marketplace_owner.py",
    )
    _git(repo, "add", ".")
    _git(repo, "commit", "-q", "-m", "add marketplace owner")

    _git(repo, "merge", "--no-edit", "owner-core")

    assert {_path: _digest(repo / _path) for _path in STABLE_PATHS} == stable_digests
    changed = set(_git(repo, "diff", "--name-only", "main..HEAD").splitlines())
    assert changed.isdisjoint(STABLE_PATHS)

    inventory = [
        path.relative_to(ROOT).as_posix()
        for path in ROOT.rglob("*")
        if path.is_file() and ".git" not in path.parts
    ]
    inventory.extend(
        path.relative_to(repo).as_posix()
        for path in repo.rglob("*")
        if path.is_file() and ".git" not in path.parts
    )
    registry = load_registry(repo / ".apm/architecture/owners", inventory)
    assert {"fixture-core-owner", "fixture-marketplace-owner"} <= {
        owner.id for owner in registry.owners
    }
